services:
  mouse:
    build:
      context: .
      dockerfile: Dockerfile.mouse
    container_name: mouse
    networks:
      - cluster_net

  cat1:
    build:
      context: .
      dockerfile: Dockerfile.cat
    container_name: cat1
    environment:
      - CAT_ID=cat1
      - CLUSTER_NODES=mouse,cat1,cat2,cat3
      - PEER_CATS=cat1,cat2,cat3
      - CAT_SERVICE_PORT=60000
    depends_on:
      - mouse
    networks:
      - cluster_net

  cat2:
    build:
      context: .
      dockerfile: Dockerfile.cat
    container_name: cat2
    environment:
      - CAT_ID=cat2
      - CLUSTER_NODES=mouse,cat1,cat2,cat3
      - PEER_CATS=cat1,cat2,cat3
      - CAT_SERVICE_PORT=60000
    depends_on:
      - mouse
    networks:
      - cluster_net

  cat3:
    build:
      context: .
      dockerfile: Dockerfile.cat
    container_name: cat3
    environment:
      - CAT_ID=cat3
      - CLUSTER_NODES=mouse,cat1,cat2,cat3
      - PEER_CATS=cat1,cat2,cat3
      - CAT_SERVICE_PORT=60000
    depends_on:
      - mouse
    networks:
      - cluster_net

networks:
  cluster_net:
    driver: bridge
