FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. cat.proto
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. mouse.proto

CMD ["python", "-u", "cat.py"]
