services:
  mouse:
    build: .
    container_name: mouse
    command: ["python", "-u", "mouse.py"]
    networks:
      - cluster_net

  cat1:
    build: .
    container_name: cat1
    environment:
      - CAT_ID=cat1
      - CLUSTER_NODES=mouse,cat1,cat2,cat3
      - PEER_CATS=cat1,cat2,cat3
      - CAT_SERVICE_PORT=60000
    command: ["python", "-u", "cat.py"]
    networks:
      - cluster_net

  cat2:
    build: .
    container_name: cat2
    environment:
      - CAT_ID=cat2
      - CLUSTER_NODES=mouse,cat1,cat2,cat3
      - PEER_CATS=cat1,cat2,cat3
      - CAT_SERVICE_PORT=60000
    command: ["python", "-u", "cat.py"]
    networks:
      - cluster_net

  cat3:
    build: .
    container_name: cat3
    environment:
      - CAT_ID=cat3
      - CLUSTER_NODES=mouse,cat1,cat2,cat3
      - PEER_CATS=cat1,cat2,cat3
      - CAT_SERVICE_PORT=60000
    command: ["python", "-u", "cat.py"]
    networks:
      - cluster_net

networks:
  cluster_net:
    driver: bridge
